FROM node:10

ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /opt/frontend

COPY frontend/package*.json ./
COPY frontend/graphics ./graphics
COPY frontend/public ./public

RUN npm install

CMD [ "npm", "start" ]
