FROM ubuntu:16.04
MAINTAINER CodaLab Worksheets <codalab.worksheets@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update; apt-get install -y \
    build-essential \
    git \
    libfuse-dev \
    libjpeg-dev \
    libmysqlclient-dev \
    mysql-client \
    python-dev \
    python-pip \
    python-software-properties \
    python-virtualenv \
    software-properties-common \
    zip;

# Install dependencies
COPY docker/compose_files/files/wait-for-it.sh /opt/wait-for-it.sh
WORKDIR /opt/codalab-worksheets
COPY worker ./worker
COPY requirements.txt ./
COPY requirements-server.txt ,/
COPY setup.sh ./
RUN  ./setup.sh server
