FROM ubuntu:16.04
MAINTAINER CodaLab Worksheets <codalab.worksheets@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa 

RUN apt-get update; apt-get install -y \
    build-essential \
    git \
    libfuse-dev \
    libjpeg-dev \
    libmysqlclient-dev \
    mysql-client \
    python3.6 \
    python3-dev \
    python3-pip \
    python-virtualenv \
    python3-software-properties \
    zip;

RUN alias python3='/usr/bin/python3.6' 

# Install dependencies
COPY docker/compose_files/files/wait-for-it.sh /opt/wait-for-it.sh
WORKDIR /opt/codalab-worksheets
RUN python3 -m pip install -U setuptools pip
COPY . /opt/codalab-server/
COPY ./worker /opt/codalab-worker/
RUN cd /opt/codalab-server && python3 -m pip install -r requirements-server.txt
RUN python3 -m pip install -e /opt/codalab-worker/
RUN python3 -m pip install -e /opt/codalab-server/

ENV CODALAB_HOME=/home/codalab

EXPOSE 2900

ENTRYPOINT ["cl"]
