FROM node:10 AS dev

ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /opt/frontend

# Install dependencies
COPY frontend/package.json ./
COPY frontend/package-lock.json ./
RUN npm ci

# Overridden in dev mode
COPY frontend .

RUN ls /opt/frontend

EXPOSE 2700

RUN npm run build

# Production mode - only copy in the build files, not
# node modules.
FROM node:10 AS prod

RUN npm install -g serve

WORKDIR /opt/frontend

COPY --from=prod build build

EXPOSE 2700
