---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codalab

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codalab
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codalab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codalab
subjects:
- kind: ServiceAccount
  name: codalab

---

apiVersion: v1
kind: Secret
metadata:
  name: codalab-service-account-secret
  annotations:
    kubernetes.io/service-account.name: codalab
type: kubernetes.io/service-account-token
