"""drop foreign key constraints on worksheet items

Revision ID: 27bd1de0c078
Revises: eb10bb49c6f
Create Date: 2015-04-23 00:40:50.997177

"""

# revision identifiers, used by Alembic.
revision = "27bd1de0c078"
down_revision = "eb10bb49c6f"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u"worksheet_item_ibfk_3", "worksheet_item", type_="foreignkey")
    op.drop_constraint(u"worksheet_item_ibfk_2", "worksheet_item", type_="foreignkey")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(u'worksheet_item_ibfk_2', 'worksheet_item', 'bundle', ['bundle_uuid'], ['uuid'])
    # op.create_foreign_key(u'worksheet_item_ibfk_3', 'worksheet_item', 'worksheet', ['subworksheet_uuid'], ['uuid'])
    pass
    ### end Alembic commands ###
