"""Add gpus column to worker

Revision ID: 46d007c5ebc3
Revises: 37e06c8c5e5d
Create Date: 2017-02-24 01:41:30.432273

"""

# revision identifiers, used by Alembic.
revision = "46d007c5ebc3"
down_revision = "37e06c8c5e5d"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("worker", sa.Column("gpus", sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker", "gpus")
    ### end Alembic commands ###
