"""Remove slots column from worker table

Revision ID: 53bcf87ddf40
Revises: 4ea0403733dc
Create Date: 2018-02-15 05:53:15.465234

"""

# revision identifiers, used by Alembic.
revision = "53bcf87ddf40"
down_revision = "4ea0403733dc"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker", "slots")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("worker", sa.Column("slots", sa.Integer(), nullable=False))
    ### end Alembic commands ###
