"""Replace cpus and gpus columns from worker table with cpuset and gpuset

Revision ID: 3f422c89878d
Revises: 53bcf87ddf40
Create Date: 2018-02-19 12:29:08.301390

"""

# revision identifiers, used by Alembic.
revision = '3f422c89878d'
down_revision = '53bcf87ddf40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'cpus')
    op.drop_column('worker', 'gpus')
    op.add_column('worker', sa.Column('cpuset', sa.LargeBinary(), nullable=False))
    op.add_column('worker', sa.Column('gpuset', sa.LargeBinary(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'cpuset')
    op.drop_column('worker', 'gpuset')
    op.add_column('worker', sa.Column('cpus', sa.Integer(), nullable=False))
    op.add_column('worker', sa.Column('gpus', sa.Integer(), nullable=False))
    ### end Alembic commands ###
