"""add preemptible column to worker

Revision ID: f720aaefd0b2
Revises: a325a0756797
Create Date: 2022-02-15 22:26:06.466720

"""

# revision identifiers, used by Alembic.
revision = 'f720aaefd0b2'
down_revision = 'a325a0756797'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('preemptible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'preemptible')
    # ### end Alembic commands ###
