#!/bin/bash

# Split an ARFF file into train and test.

if [ $# != 4 ]; then
  echo "Usage: $0 <input data path> <train path> <test path> <number of folds; hold out one fold for test>"
  exit 1
fi

# Train
echo "Splitting into train..."
`dirname $0`/runjava weka.filters.supervised.instance.StratifiedRemoveFolds -i $1 -o $2 -c last -N $4 -F 1 -V || exit 1
[ -e "$2" ] || exit 1  # Check because Weka programs don't return proper exit codes

# Test
echo "Splitting into test..."
`dirname $0`/runjava weka.filters.supervised.instance.StratifiedRemoveFolds -i $1 -o $3 -c last -N $4 -F 1 || exit 1
[ -e "$3" ] || exit 1  # Check because Weka programs don't return proper exit codes
