FROM nvidia/cuda:9.2-runtime
MAINTAINER CodaLab Team "codalab.worksheets@gmail.com"

# Installed packages:

# CUDA 9.2 Toolkit &  Runtime Libraries
# python (2.7)
# python3.7
# pip
# pip3
# cmake
# numpy
# scipy
# matplotlib
# pandas
# sympy
# nose
# spacy
# spacy-en
# tqdm
# wheel
# scikit-learn
# scikit-image
# dlib
# OpenAI gym[all]
# NLTK (no data)
# tensorflow GPU
# keras
# pytorch GPU
# torchvision

RUN apt-get -y update; apt-get -y upgrade;
RUN apt-get -y install git;
RUN apt-get -y install python2.7;
RUN apt-get -y install python-pip;
RUN apt-get -y install python-dev;
RUN apt-get -y install python-software-properties;
RUN apt-get -y install python-tk;
RUN apt-get -y install software-properties-common;
RUN apt-get -y install build-essential;
RUN apt-get -y install cmake;
RUN apt-get -y install default-jdk;
RUN apt-get -y install libhdf5-dev;
RUN apt-get -y install swig;

RUN apt-get clean && apt-get autoremove

RUN pip install -U pip
RUN pip install -U \
      spacy \
      tqdm \
      wheel \
      scikit-learn \
      scikit-image \
      dlib \
      gym[all] \
      nltk \
      numpy \
      scipy \
      matplotlib \
      pandas \
      sympy \
      nose;

RUN python -m spacy download en

# Set up python3

RUN add-apt-repository -y ppa:deadsnakes/ppa;
RUN apt-get -y update:
RUN apt-get -y install python3.7;
RUN apt-get -y install python3-pip;
RUN apt-get -y install python3-dev;
RUN apt-get -y install python3-software-properties;

RUN pip3 install -U pip
RUN pip3 install -U \
      spacy \
      tqdm \
      wheel \
      scikit-learn \
      scikit-image \
      dlib \
      gym[all] \
      nltk \
      numpy \
      scipy \
      matplotlib \
      pandas \
      sympy \
      nose;

RUN python3 -m spacy download en


# GPU-specific commands

RUN pip install -U \
      tensorflow-gpu \
      tensorboard \
      keras

RUN pip install -U http://download.pytorch.org/whl/cu92/torch-0.4.1-cp27-cp27mu-linux_x86_64.whl || pip install -U http://download.pytorch.org/whl/cu92/torch-0.4.1-cp27-cp27m-linux_x86_64.whl
RUN pip install torchvision


RUN pip3 install -U \
      tensorflow-gpu \
      tensorboard \
      keras

RUN pip3 install http://download.pytorch.org/whl/cu92/torch-0.4.1.post2-cp37-cp37m-linux_x86_64.whl
RUN pip3 install torchvision
