version: '3.5'

x-non-blocking-logging:
  &non-blocking-logging
  driver: json-file
  options:
    mode: non-blocking

services:
  mysql:
    image: mysql:5.5.53
    environment:
      - MYSQL_ROOT_PASSWORD=${CODALAB_MYSQL_ROOT_PWD}
      - MYSQL_DATABASE=codalab_bundles
      - MYSQL_USER=${CODALAB_MYSQL_USER}
      - MYSQL_PASSWORD=${CODALAB_MYSQL_PWD}
    networks:
      - service
    logging:
      *non-blocking-logging

  rest-server:
    depends_on:
      - mysql
