version: '3.5'

x-codalab-home-mount:
  &codalab-home-mount
  type: bind
  source: ${CODALAB_HOME}
  target: ${CODALAB_HOME}

services:
  rest-server:
    user: ${CODALAB_UID}
    volumes:
      - *codalab-home-mount

  bundle-manager:
    user: ${CODALAB_UID}
    volumes:
      - *codalab-home-mount
