name: Release
on:
  release:
    types: [published]

jobs:
  release_to_pypi:
    name: Release to PyPi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-
      - run: pip install -r requirements.txt
      - run: pip install twine
        # remove first character (v) from tag name
      - run: ./scripts/ci-deploy.sh ${TAG#?}
        env:
          TAG: ${{ github.event.release.tag_name }}
          CODALAB_DOCKER_USERNAME: ${{ secrets.CODALAB_DOCKER_USERNAME }}
          CODALAB_DOCKER_PASSWORD: ${{ secrets.CODALAB_DOCKER_PASSWORD }}
      # Uses trusted publishing to authenticate to PyPI: see https://docs.pypi.org/trusted-publishers/using-a-publisher/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
