name: Release
on:
  release:
    types: [published]

jobs:
  release_to_pypi:
    name: Release to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - run: pip install twine
        # remove first character (v) from tag name
      - run: ./scripts/travis-deploy.sh ${TAG#?}
        env:
          TAG: ${{ github.event.release.tag_name }}
          CODALAB_DOCKER_USERNAME: ${{ secrets.CODALAB_DOCKER_USERNAME }}
          CODALAB_DOCKER_PASSWORD: ${{ secrets.CODALAB_DOCKER_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}