FROM node:14-slim

ENV NPM_CONFIG_LOGLEVEL warn

ARG dev=false

RUN npm install -g serve

WORKDIR /opt/frontend

# Install dependencies
COPY frontend/package.json ./
COPY frontend/package-lock.json ./
COPY setup_frontend.js setup_frontend.js 
RUN npm ci

# Overridden in dev mode
COPY frontend .

# Build static files (skipped in dev mode)
RUN if [ "$dev" = "false" ] ; then \
    cat public/index.prod.html >| public/index.html &&\
    npm run build --production; \
    fi

EXPOSE 2700
